### PR TITLE
upgrade to phpunit 6

### PR DESCRIPTION
**Pull request by bendavies**
ref: https://github.com/daylerees/scientist/pull/19

### CODE REVIEW

**Comment by rodnaph** [comment]
Oh, Ben...

**Comment by danhanly** [comment]
Either `use` import the classes, or `\` the root namespace :+1:

**Comment by bendavies** [comment]
actually this is slightly annoying to support all php versions. how about a new major version for php 7.x and up @daylerees @daylerees  ?

**Comment by rodnaph** [comment]
That would help on https://github.com/daylerees/scientist/pull/20

**Comment by daylerees** [comment]
Might make sense to tag a new major release with this, yup. Up the requirements. 🤔

**Comment by daylerees** [comment]
I'll see if I can find some time later tonight to get these two PRs in, fix up the tests and tag a new version. Thanks chaps. 🤘

**Comment by daylerees** [comment]
Changed target to `develop` to merge with Rod's other changes and then can fix tests for the new version there. (Just in case any nutters are versioned against dev-master)

**Pull request merged**
