### PR TITLE
Capture output for experiments

### PR DESCRIPTION
**Pull request by meadsteve**
For older code with a bunch of `echo`s in it it would be nice to be able to capture and compare what would go to output.

What do you think?

### CODE REVIEW

**Comment by daylerees** [comment]
Interesting idea mate. I wonder if the matcher should act on this value. Hrrrrm!

**Comment by meadsteve** [comment]
ahhh I hadn't considered the matchers.  Does the standard matcher actually do anything on the Result object by default? All I can see is the === comparison which would `false` for a control `Result` and trial `Result` anyway.

**Comment by danhanly** [comment]
@meadsteve Matchers can compare like to like, but you can also develop them to fit a more specific set of circumstances.

For reference look at [my utility matchers repository](https://github.com/danhanly/scientist-utility-matcher), where I add matchers to do a range of different things.

**Comment by meadsteve** [comment]
@danhanly well nothing I've done conflicts with any of your matchers so that's good.

**Comment by danhanly** [comment]
@meadsteve I wasn't implying you did conflict, but rather was just trying to show you an example of how matchers can do something a bit more than just like->like matching :smile:

**Pull request closed without merging**
